# Generated by Django 3.2.9 on 2021-12-28 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_entries', '0003_alter_post_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
